stack.yml
root@dev-server01 /myworkspace/docker-swarm # cat stack.yml
version: "3"
services:
  postgresql:
   image: postgres:latest
   volumes:
     - /opt/data/postgresql:/var/lib/postgresql/data
   networks:
     - proxy-network
   ports:
     - 5432:5432
   deploy:
     replicas: 1
#     placement:
#       constraints: [node.role == node1]
#     restart_policy:
#       condition: on-failure
#       max_attempts: 3
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin@123
  nginx:
   image: nginx:1.19-alpine
   ports:
     - 8080:80
   deploy:
     mode: replicated
     replicas: 1
   volumes:
     - /usr/share/nginx/html:/usr/share/nginx/html
networks:
   proxy-network:
     external: true
